# eslint yml/sort-keys: 'error'

catalog:
  '@vue/compiler-core': alpha
  '@vue/compiler-dom': alpha
  '@vue/compiler-sfc': alpha
  '@vue/language-core': 2.0.28
  '@vue/reactivity': alpha
  '@vue/runtime-core': alpha
  '@vue/runtime-dom': alpha
  '@vue/shared': alpha
  unplugin: ^1.11.0
  vite: ^5.3.4
  vue: alpha
  vue-tsc: 2.0.28
packages:
  - packages/*
  - playground/*
  - '!playground/nuxt'
  - docs
